### DISCUSSION TITLE
Templating inside a ConfigMap

### DISCUSSION THREAD

**Discussion by andreasgerstmayr** [kyverno/chainsaw#1120] [Q&A]
Is it possible to template the namespace in a ConfigMap value?
E.g.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-configmap
data:
  config.yaml: |
    exporters:
      otlp:
        endpoint: tempo-sample-gateway.$namespace.svc.cluster.local:4317
```
?

I have to specify the full name, because the TLS certificate is only valid for `tempo-sample-gateway.$namespace` and `tempo-sample-gateway.$namespace.svc.cluster.local` but not for `tempo-sample-gateway`.

https://kyverno.io/blog/2024/02/15/kyverno-chainsaw-0.1.4-awesome-new-features/#good-example-the-chainsaw-v014-way shows a way to template a field, but in this case, creating a jmespath expression of the multi-line field makes stuff less readable.
