### DISCUSSION TITLE
FileRef - url to private repo

### DISCUSSION THREAD

**Discussion by uemk** [kyverno/chainsaw#1343] [Q&A]
Can FileRef point to the url which is not publicly available? I'm trying to use analogical example to this one:
```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: example
spec:
  steps:
  - try:
    # ...
    - apply:
        file: https://raw.githubusercontent.com/kyverno/chainsaw/main/testdata/step/configmap.yaml
    # ...
```

but instead of using github I'm using gitlab url. It works only if I make repo public. In case of private repository I get an error:
```bash
        === ERROR
        error downloading content: timed out waiting for the condition
```

I tried to provide an access token in url but without success.
