### ISSUE TITLE
[Feature] Add Operation to query the internal Prometheus instance

### ISSUE THREAD

**Issue by pvdvreede** [kyverno/chainsaw#1130]
### Problem Statement

I want to be able to assert that a certain operation within the cluster is completed within x seconds, or is completed with less than x errors. This information is not available to Chainsaw or is an aggregate over x period of time and so is hard or impossible for Chainsaw to gather on its own.

### Solution Description

Have a prometheus running within the cluster scraping pods and aggregating this information over time. Then have a operation in Chainsaw that can run some PromQL against that Prometheus and assert if a threshold has been reached.

### Alternatives

Currently I used a script like this to achieve the solution - this assumes your Chainsaw tests are running out side the Cluster:

```yaml
- script:
        timeout: 10s
        env:
          - name: query
            value: "histogram_quantile%280.999%2C+sum%28rate%28sidecar_injection_time_seconds_bucket%5B5m%5D%29%29+by+%28le%29%29"
        content: |
          kubectl -n monitoring port-forward svc/prometheus-server 8091:80 > /dev/null &
          sleep 0.5
          wget -O - "http://localhost:8091/api/v1/query?query=${query}"
          kill %1
        check:
          (json_parse($stdout).status): success
          (json_parse($stdout).data.resultType): vector
          (length(json_parse($stdout).data.result)): 1
          (to_number(json_parse($stdout).data.result[0].value[1]) < `1.0`): true
```

This works, but is verbose and error prone, so be great to have a specific operation for this.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
I added a proxy helper that should do the trick:
```yaml
    - proxy:
        apiVersion: v1
        kind: Service
        namespace: monitoring
        name: prometheus-serve
        port: '80'
        path: (join('=', ['/api/v1/query?query', $query]))
```
