### ISSUE TITLE
How can I test output commands using helm and keeping the file ordination during execution?

### ISSUE THREAD

**Issue by lucasjct** [kyverno/chainsaw#1133]
### Describe your question

Hello everyone! Thanks for chainsaw, is a great tools! 🥳 

I'm attempting to test the output for several Helm commands. I'm conducting these tests separately for each file. However, my last file verifies the output for uninstalling the application. This has posed a challenge because the uninstallation should be the final test command, but it's being executed among other tests and disrupting the pipeline

How can I test it maintaining the files separated? 

Below is my current directories. The expected behavior, wold be run `9-uninstall-zora` like the last test?

```
├── 0-helm-install-test
│   └── chainsaw-test.yaml
├── 1-misc-test
│   └── chainsaw-test.yaml
 ....
├── 8-set-timout-for-scan
│   └── chainsaw-test.yaml
├── 9-uninstall-zora
│   └── chainsaw-test.yaml
├── config.yaml
```

My config file contains:
```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  timeouts:
    apply: 45s
    assert: 20s
    cleanup: 45s
    delete: 25s
    error: 10s
    exec: 45s
  skipDelete: false
  failFast: true
  parallel: 1
```

and my test for helm uninstall:

```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: delete-zora
spec:
  steps:
  - try:
    - script:
     #You can uninstall Zora and its components by uninstalling the Helm chart installed.
        content: helm uninstall zora -n zora-system
        check:
        # This check ensures that zora has been uninstalled correctly.
          ($stdout): |- 
            release "zora" uninstalled
```

Thank you very much!

### chainsaw version Version

v0.1.8

### Additional context

I'm using like reference this part of documentation:
https://kyverno.github.io/chainsaw/latest/examples/test-output/
