### ISSUE TITLE
[Feature] For loop in a test

### ISSUE THREAD

**Issue by sandert98** [kyverno/chainsaw#1143]
### Problem Statement

When checking the status of a lot of components, where only the name differs, it can be useful to be able to create a for loop. So you only have to declare once the assertion you want to check, and a list with names. For example in this simple check: 

```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: running-deployments
spec:
  template: true
  timeouts:
    assert: 120s
  steps:
    - try:
        - assert:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: app1
              status:
                (readyReplicas == replicas): true
                (conditions[?type == 'Available']):
                  - status: 'True'
    - try:
        - assert:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                  name: app2
              status:
                (readyReplicas == replicas): true
                (conditions[?type == 'Available']):
                  - status: 'True'
```

### Solution Description

There are many ways this could be implemented. This is just a idea

```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: running-deployments
spec:
  bindings:  <-- Because bindings is already a option in Chainsaw, maybe its good to use it also for lists
  - name: deployments
     values: app1, app2
  template: true
  timeouts:
    assert: 120s
  steps:
    for deploy in ($deployments) <-- Start for loop
    - try:
        - assert:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: ($deploy) <-- The selected deployment
              status:
                (readyReplicas == replicas): true
                (conditions[?type == 'Available']):
                  - status: 'True'
```

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by nkuacac** [comment]
```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: app.tolerations
spec:
  template: true
  description: checking tolerations
  namespace: default
  steps:
    - description: "step-1"
      try:
        - description: "toleration"
          script:
            content: kubectl get pods  -ojson
            outputs:
              - name: podList
                value: (json_parse($stdout))
        - assert:
            resource:
              ($podList):
                ~.(items):
                  spec:
                    tolerations:
                      - effect: NoExecute
                        key: node.kubernetes.io/unreachable
                        operator: Exists
                        tolerationSeconds: 30
                      - effect: NoExecute
                        key: node.kubernetes.io/not-ready
                        operator: Exists
                        tolerationSeconds: 30
```
