### ISSUE TITLE
Wildcard / random pod name check

### ISSUE THREAD

**Issue by gerbil** [kyverno/chainsaw#1156]
### Describe your question

Hi.  please advise how to check for random pod name?

```
- assert:
    resource:
      apiVersion: v1
      kind: Pod
      metadata:
        namespace: test
        name: applicationdeployment-backend-*-*
```

### chainsaw version Version

v0.1.0
