### ISSUE TITLE
[Bug]missing KUBERNETES_MASTER env in ci

### ISSUE THREAD

**Issue by whg517** [kyverno/chainsaw#1159]
### chainsaw version Version

v0.1.8

### Description

When I am in a new operating environment, I create a k8s cluster using kind, specifying the kubeconfig location. Then run chansaw test to specify the cluster configuration through the chansaw configuration file, and the following error occurs:

```
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

### Steps to reproduce

1.  env

```
KIND_VERSION ?= v0.22.0

KINDTEST_K8S_VERSION ?= 1.26.14

KIND_IMAGE ?= kindest/node:v${KINDTEST_K8S_VERSION}
KIND_KUBECONFIG ?= kind-kubeconfig-$(KINDTEST_K8S_VERSION)
KIND_CLUSTER_NAME ?= ${PROJECT_NAME}-$(KINDTEST_K8S_VERSION)
```

2.

```
$(KIND) create cluster --config test/e2e/kind-config.yaml --image $(KIND_IMAGE) --name $(KIND_CLUSTER_NAME) --kubeconfig $(KIND_KUBECONFIG) --wait 120s
```

3.

```
$(CHAINSAW) test --cluster cluster-1=$(KIND_KUBECONFIG) --test-dir ./test/e2e --config .chainsaw.yaml 
```

---

`./test/e2e/kind-config.yaml`

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.26.14@sha256:5d548739ddef37b9318c70cb977f57bf3e5015e4552be4e27e57280a8cbb8e4f
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 18080
    protocol: TCP
  - containerPort: 443
    hostPort: 18443
    protocol: TCP

```

`.chainsaw.yaml`

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  timeouts:
    apply: 120s
    assert: 120s
    cleanup: 120s
    delete: 120s
    error: 10s
    exec: 45s
  skipDelete: false
  failFast: true
  parallel: 1 # use 1 concurrent to test, to voide multiple csi driver conflict

```

### Expected behavior

i want everythings is ok.

BUT I GOT ERROR

### Screenshots

```
❯ make kind-create
/opt/homebrew/bin/kind create cluster --config test/e2e/kind-config.yaml --image kindest/node:v1.26.14 --name secret-operator-1.26.14 --kubeconfig kind-kubeconfig-1.26.14 --wait 120s
Creating cluster "secret-operator-1.26.14" ...
 ✓ Ensuring node image (kindest/node:v1.26.14) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Waiting ≤ 2m0s for control-plane = Ready ⏳ 
 • Ready after 13s 💚
Set kubectl context to "kind-secret-operator-1.26.14"
You can now use your cluster with:

kubectl cluster-info --context kind-secret-operator-1.26.14 --kubeconfig kind-kubeconfig-1.26.14

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
# make kind-setup KUBECONFIG=kind-kubeconfig-1.26.14
❯ 
❯ make chainsaw-test
/Users/kevin/workspace/develop/golang/bin/chainsaw test --cluster cluster-1=kind-kubeconfig-1.26.14 --test-dir ./test/e2e --config .chainsaw.yaml 
Version: v0.1.8
Loading config (.chainsaw.yaml)...
- Using test file: chainsaw-test
- TestDirs [./test/e2e]
- SkipDelete false
- FailFast true
- ReportFormat ''
- ReportName 'chainsaw-report'
- Namespace ''
- FullName false
- IncludeTestRegex ''
- ExcludeTestRegex ''
- ApplyTimeout 2m0s
- AssertTimeout 2m0s
- CleanupTimeout 2m0s
- DeleteTimeout 2m0s
- ErrorTimeout 10s
- ExecTimeout 45s
- Parallel 1
- Clusters map[cluster-1:{kind-kubeconfig-1.26.14 }]
- NoCluster false
Loading tests...
- search-in-default-ns (test/e2e/search-in-default-ns)
- search-with-pod (test/e2e/search-with-pod)
- tls (test/e2e/tls)
Loading values...
Running tests...
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
make: *** [chainsaw-test] Error 1
```

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.
