### ISSUE TITLE
[Feature] Interactive debug when an assertion fails

### ISSUE THREAD

**Issue by seanpoulter** [kyverno/chainsaw#1244]
### Problem Statement

* I don't have time to debug when an assertion fails
* I haven't been successful using `command` or `script` to wait for input like `read -n1`

### Solution Description

I'd like to be able to either:

Option 1) Configure a Test to wait for the user's input to `debug` like this:

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: example
spec:
  catch:
  - debug
```

### Alternatives

Option 2) Enable that "debug on failure" mode

Option 3) We could extend `sleep` to interruptible

### Additional Context

I'm happy to help. :)

I'm inspired by this developer experience with WebdriverIO - https://webdriver.io/docs/api/browser/debug/.

### Slack discussion

https://kubernetes.slack.com/archives/C067LUFL43U/p1714622801505569

### Research

- [X] I have searched other issues in this repository and mine is not recorded.
