### ISSUE TITLE
[Bug] YAML anchors are not being rendered when using '<<:'

### ISSUE THREAD

**Issue by EladDolev** [kyverno/chainsaw#1275]
### chainsaw version Version

v0.2.0

### Description

When using overrides with the characters '<<:' to add more values, or override existing ones chainsaw fail to parse the YAML with the following
```
Error: failed to parse document (yaml: unmarshal errors:
  line 26: key "spec" already set in map)
```

### Steps to reproduce

```yaml
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: &name yaml-anchors
spec:
  namespace: &namespace default
  steps:
  - name: *name
    try:
    - apply:
        resource: &resource
          apiVersion: v1
          kind: Pod
          metadata:
            name: *name
            namespace: *namespace
          spec:
            containers:
            - name: main
              image: alpine
    - assert:
        resource:
          <<: *resource
          spec:
            restartPolicy: Always
        timeout: 1s
```

### Expected behavior

YAML should be rendered as it is legit

### Slack discussion

https://kubernetes.slack.com/archives/C067LUFL43U/p1715689590196259

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.
