### ISSUE TITLE
[Bug] namespaceTemplate in config file ignored

### ISSUE THREAD

**Issue by mikebryant** [kyverno/chainsaw#1278]
### chainsaw version Version

v0.2.0

### Description

I'm trying to set up a namespaceTemplate to add a label

The ephemeral Namespaces created don't have the label

### Steps to reproduce

```
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: default
spec:
  namespaceTemplate:
    metadata:
      labels:
        # Cleanup the ephemeral namespaces after 15 minutes
        # Useful if the chainsaw test is interrupted
        cleanup.kyverno.io/ttl: 15m
```

### Expected behavior

I expected the template to take effect

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.
