### ISSUE TITLE
[Feature] Support $test.name as an in-built binding 

### ISSUE THREAD

**Issue by MattHodge** [kyverno/chainsaw#1471]
### Problem Statement

I am testing Argo Workflows, and need to provide a randomly generated name for the workflow.

I'd still like to have an idea of which workflow was triggered by the test to allow troubleshooting. 

To do this, I am setting 2 bindings:

- `test_name` which is the name of the test which will be
- `wf_name`, which uses `(join('-', ['test', $test_name, random('[a-z]{5}')]))`

The `test_name` always matches the `.metadata.name` field, meaning I have duplication in my test, see below as an example:

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: slack-post-message # This value is duplicated
spec:
  template: true
  namespace: wf-general

  bindings:
    - name: test_name
      value: slack-post-message # This value is duplicated

    - name: wf_name
      value: (join('-', ['test', $test_name, random('[a-z]{5}')])) # I'd like to reference the `.metadata.name` here instead of $test_name

  steps:
    - try:
      - apply:
          file: apply.yaml

      - wait:
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          name: ($wf_name)
          timeout: 1m
          for:
            condition:
              name: Completed
              value: 'True'

      - assert:
          file: assert.yaml
```

### Solution Description

Provide an additional binding such as `$test.name` which would allow accessing the name of the test in other bindings. 

### Slack discussion

https://kubernetes.slack.com/archives/C067LUFL43U/p1716914766877039

### Research

- [X] I have searched other issues in this repository and mine is not recorded.
