### ISSUE TITLE
[Bug] Assert not waiting until assertion succeeds

### ISSUE THREAD

**Issue by patst** [kyverno/chainsaw#1823]
### chainsaw version Version

v0.2.8

### Description

Hey there,
just moving from KUTTL to chainsaw (thanks for the great tool!).

I am not completely sure, if my issue is really a bug or a conceptional misunderstanding.

I am creating resources in a step and then trying to check the status of the resources for the expected attributes.

The tests sometimes succeeds, but often are failing due to assertions raising errors due to not matching my expectations.
I think it is, because the fields which are tested are not yet in the status auf the resources.

My understanding was, that the `assert` parts are retried until the timeout is reached. Am I wrong?

### Steps to reproduce

I have the following test:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: pstest-simple
spec:
  bindings:
    - name: test_name
      value: (join('-',['docint', random('[a-z]{5}')]))
  catch:
    - command:
        entrypoint: kubectl
        args:
          - "get"
          - "-o"
          - "yaml"
          - "-n"
          - "default"
          - "MyResource"
  steps:
    - try:
        - apply:
            file: 00-install.yaml
        - assert:
            file: 00-assert.yaml
            timeout: 10m
```

The install file (00-install.yaml):
```yaml
# 00-install.yaml
apiVersion: my.resources.com/v1alpha1
kind: MyResource
metadata:
  name: ($test_name)
spec: { }
```

And the assertion:
```yaml
apiVersion: my.resources.com/v1alpha1
kind: MyResource
metadata:
  name: ($test_name)
spec: { }
status:
  (conditions[?type == 'Ready']):
    - status: "True"
  (regex_match('[\d\w]{4}', randomSuffix)): true
  privateEndpoint:
    (regex_match('^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$', privateIpAddress)): true
```

The resource to be checked:

```yaml
apiVersion: my.resources.com/v1alpha1
kind: MyResource
metadata:
  finalizers:
  - finalizer.apiextensions.crossplane.io
  name: pstest
  namespace: default
spec:
  compositeDeletePolicy: Background
  compositionRef:
    name: crossplane-composition
  compositionRevisionRef:
    name: crossplane-composition-fad1551
  compositionUpdatePolicy: Automatic
  resourceRef:
    apiVersion: my.resources.com/v1alpha1
    kind: MyResource
    name: pstest
status:
  conditions:
  - lastTransitionTime: "2024-08-01T18:15:33Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-01T18:17:53Z"
    reason: Creating
    status: "False"
    type: Ready
#  privateEndpoint:
#    conditions:
#    - lastTransitionTime: "2024-08-01T18:17:29Z"
#      reason: Available
#      status: "True"
#      type: Ready
#    - lastTransitionTime: "2024-08-01T18:16:44Z"
#      reason: ReconcileSuccess
#      status: "True"
#      type: Synced
#    - lastTransitionTime: "2024-08-01T18:17:27Z"
#      reason: Success
#      status: "True"
#      type: LastAsyncOperation
#    privateIpAddress: 10.161.129.69
  randomSuffix: vpjm
```

The part with the comments is not available directly, only after crossplane created the corresponding resources and copied the attributes to the status.

### Expected behavior

I would expect the `assert` being retried, until it success completely or the timeout of 10 minutes is reached.

### Logs

```Shell
| 16:31:10 | pstest-simple | step-1    | ASSERT    | RUN   | my.resources.com/v1alpha1/MyResource @ default/docint-oxefb
    | 16:32:20 | pstest-simple | step-1    | ASSERT    | ERROR | my.resources.com/v1alpha1/MyResource @ default/docint-oxefb
        === ERROR
        -----------------------------------------------------------------------------------------
        my.resources.com/v1alpha1/MyResource/default/docint-oxefb
        -----------------------------------------------------------------------------------------
        * status.(conditions[?type == 'Ready'])[0].status: Invalid value: "False": Expected value: "True"
        * status.privateEndpoint: Required value: field not found in the input object
        
        --- expected
        +++ actual
        @@ -4,10 +4,5 @@
           name: docint-oxefb
           namespace: default
         spec: {}
        -status:
        -  (conditions[?type == 'Ready']):
        -  - status: "True"
        -  (regex_match('[\d\w]{4}', randomSuffix)): true
        -  privateEndpoint:
        -    (regex_match('^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$', privateIpAddress)): true
        +status: {}
```

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.
