### ISSUE TITLE
[Bug]template BasePath should be the path of template, rather than test.BasePath

### ISSUE THREAD

**Issue by nkuacac** [kyverno/chainsaw#1851]
### chainsaw version Version

v0.2.8

### Description

the operation resource file is relate to template,  in test will not find the resource file
```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: StepTemplate
metadata:
  name: dispatch-workloads
spec:
  try:
    - description: "create curt"
      apply:
        file: (join('/', ['resources', 'customUnitedResourceTemplate.yaml']))
    - description: "assert curt"
      assert:
        file: (join('/', ['resources', 'customUnitedResourceTemplate.yaml']))
    - description: "create cur"
      apply:
        file: (join('/', ['resources', $namespace, 'customUnitedResource.yaml']))
    - description: "assert cur"
      assert:
        file: (join('/', ['resources', $namespace, 'customUnitedResource.yaml']))
```

### Steps to reproduce

1. create a template like above.
2. create a test use the template.
```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: test
spec:
  - description: "step-5"
    use:
      template: '../../curs/sample/step_init_data_cluster.yaml'
```

### Expected behavior

test in different path can use the template

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.
