### ISSUE TITLE
[Question] which is the best way to patch pods created by controllers  

### ISSUE THREAD

**Issue by nkuacac** [kyverno/chainsaw#1852]
### Describe your question

After i  create a deploy with 3 replicas,  I want to patch pods of deploy to add annotations.  Thanks for reply.

### chainsaw version Version

v0.2.8

**Comment by eddycharly** [comment]
You can probably use a `patch`.

**Comment by nkuacac** [comment]
> You can probably use a `patch`.

do you have example to patch pods array.

**Comment by eddycharly** [comment]
specify the labels to lookup the target pods and the annotations you want to add.
```
- patch:
    resource:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
           ...
        annotations:
            foo: bar
```
