### ISSUE TITLE
[Question] String interpolation for testing ConfigMap data

### ISSUE THREAD

**Issue by aaronborden-rivian** [kyverno/chainsaw#1866]
### Describe your question

I have ConfigMap data that I want to verify is correct. The content might include interpolated values, like the namespace. `(join('-', [$values.myvar, 'hardcoded-suffix']))` works fine for small strings, but if you have a multi-line string, this becomes very cumbersome.

What is the recommended approach for validating string data like this?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
 data:
   config.ini: |
    [main]
    host=storage.service.($namespace):1234
    
    [logging]
    level=($logLevel)
```
    

### chainsaw version Version

v0.2.8
