### ISSUE TITLE
[Bug] Lint doesn't work with chainsaw.kyverno.io/v1alpha2

### ISSUE THREAD

**Issue by camaeel** [kyverno/chainsaw#1884]
### chainsaw version Version

v0.2.8

### Description

`chainsaw lint` is not able to lint v1alpha2 Configuration document

### Steps to reproduce

1. Create a config:
    ```yaml
    # yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha2.json
    apiVersion: chainsaw.kyverno.io/v1alpha2
    kind: Configuration
    metadata:
      name: example
    spec:
    
      cleanup:
        skipDelete: false
    ```
2. Run: `chainsaw lint configuration -f config.yaml`
3. Output is:
    ```
    Processing input...
    The schema is not valid. See errors:
    - apiVersion: apiVersion must be one of the following: "chainsaw.kyverno.io/v1alpha1"
    - spec: Additional property cleanup is not allowed
    Error: document is not valid
    ```

### Expected behavior

Linter should correctly validate Configuration from apiVersion: chainsaw.kyverno.io/v1alpha2

### Logs

```Shell
Processing input...
The schema is not valid. See errors:
- apiVersion: apiVersion must be one of the following: "chainsaw.kyverno.io/v1alpha1"
- spec: Additional property cleanup is not allowed
Error: document is not valid
```

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.
