### ISSUE TITLE
[Feature] value for wait should be optional

### ISSUE THREAD

**Issue by camaeel** [kyverno/chainsaw#1885]
### Problem Statement

I would like to check if filed: `.status.loadBalancer.ingress[0].ip` is set. I don't want to check the value. 

I ended up with 
```
        - script:
            env:
              - name: namespace
                value: ($namespace)
            content: |
              kubectl wait ingresses.v1.networking.k8s.io --for=jsonpath={.status.loadBalancer.ingress[0].ip} --all -n $namespace --timeout 1m0s
```

but would be great to execute this with `wait` DSL:

```
            apiVersion: networking.k8s.io/v1
            timeout: 1m
            kind: Ingress
            for:
              jsonPath:
                path: "{.status.loadBalancer.ingress[0].ip}"
```

### Solution Description

Implment a way to wait for presence of a field, without checking contents. 

### Alternatives

Use script/command as in the description above.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.
