### ISSUE TITLE
[Question] Run test on multiple clusters

### ISSUE THREAD

**Issue by pgmgb** [kyverno/chainsaw#2125]
### Describe your question

Not sure, if I'm going in the wrong direction here - so let me know if there is another way to achieve this :-)

We have two different cluster types (hyperscaler) and our tests need to be executed with also two different permission sets (admin and customer). 

Based on the documentation, I solved the hyperscaler "issue" with labels:
```bash
chainsaw test --selector "test-target in (all, h1)"...
```
```yaml
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: my-test
  labels:
    test-target: all # all, h1, h2
(...)
```

The two different permissions would be handled with the `cluster` configuration. \
`$KUBECONFIG_PATH` will be the same file with one cluster but two different users and contexts.
```bash
chainsaw test \
    --cluster customer=$KUBECONFIG_PATH:customer \
    --cluster admin=$KUBECONFIG_PATH:admin \
    --no-cluster
```
```yaml
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: my-test
spec:
  cluster: customer
(...)
```
There is now the use case, that certain tests should be executed in the `customer` and `administrator` contexts. \
At the moment, I see the only option to duplicate the test and adjusting the `cluster: customer` to `cluster: admin` because `cluster` is a string and not a list.

Are there any suggestions on how to handle this?

### chainsaw version Version

v0.2.11

**Comment by eddycharly** [comment]
Thanks for reporting!

You can use the `scernarios` feature (unfortunately i don't think it's documented yet):

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: my-test
spec:
  scenarios:
  - bindings:
    - name: cluster
      value: customer
  - bindings:
    - name: cluster
      value: administrator
  cluster: ($cluster)
```
