### ISSUE TITLE
[Question] Assert that a label does not exist in the namespace

### ISSUE THREAD

**Issue by pgmgb** [kyverno/chainsaw#2131]
### Describe your question

I try to test, that a certain label is not present on a namespace.
I'm sure there is a "simpler" way to achieve this?
```yaml
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: ns-label-test
spec:
  namespace: chainsaw-ns-label-test
  namespaceTemplate:
    metadata:
      labels:
        # my-label: test
  steps:
        - assert:
            timeout: "3s"
            resource:
              (x_k8s_get($client, 'v1', 'Namespace', $namespace, $namespace)):
                (contains(keys(metadata.labels), 'my-label')): false
```

### chainsaw version Version

v0.2.11

**Comment by amabilee** [comment]
I think this can be simplified by leveraging Kyverno policies directly, as Kyverno is designed to manage Kubernetes resources with policies.

**Comment by amabilee** [comment]
I was searching but there isn't a significantly more optimized way to write the test. The provided example is already streamlined and efficient.

While using policies with Kyverno simplifies the enforcement of rules directly in your Kubernetes cluster, it might not necessarily simplify the Chainsaw testing configuration itself.
Chainsaw is a testing framework, and while Kyverno policies can enforce constraints, you still need to write tests to verify that these constraints are being met.

Hope that helps!

**Comment by eddycharly** [comment]
Use an `error`:

```yaml
        - error:
            timeout: "3s"
            resource:
              apiVersion: v1
              kind: Namespace
              metadata:
                labels:
                  # the label that must not be present
                  my-label: test
```
