### ISSUE TITLE
[Feature] Option to not log the script/command

### ISSUE THREAD

**Issue by cbandy** [kyverno/chainsaw#2134]
### Problem Statement

I have some rather long `script` steps that occupy a lot of vertical space in my `chainsaw test` logs. The script's content is stored in my test suite, so seeing it in the logs is more noise than helpful.

### Solution Description

I would like a way to omit the `COMMAND` section of the logs from specific operations in my test suite:

```
        === COMMAND
        /bin/sh -c …
```

I _do_ want to see the `stdout` and `stderr` from these operations. Perhaps another field similar to the existing `skipLogOutput` field?

```yaml
try:
  - script:
      skipCommandOutput: true
      skipLogOutput: false
      content: |
        : my long script
```

### Alternatives

🤔 A stack of booleans... Does this call for an enum?

```yaml
script:
  log: null            # current behavior of `skipLogOutput: false`; COMMAND, STDOUT, and STDERR sections
  log: Command         # current behavior of `skipLogOutput: true`; only COMMAND
  log: CombinedOutput  # only STDOUT and STDERR
  log: StandardOutput  # only STDOUT
  log: StandardError   # only STDERR
```

### Research

- [X] I have searched other issues in this repository and mine is not recorded.
