### ISSUE TITLE
[Feature] Customize prefix of name of the ephemeral generated namespace

### ISSUE THREAD

**Issue by ChrisV404** [kyverno/chainsaw#2155]
### Problem Statement

Currently I have a need to run tests in a namespace with a certain prefix in the name. I'd still want to maintain the random name generated by Chainsaw as the suffix. The tests require certain Roles that exist in my cluster. The prefix will enforce isolation to block access of the namespace to anyone (or anything) that don't possess the valid Role. 

### Solution Description

I'd like to configure the prefix of the namespace at the Test spec level and in the Configuration file.

Potential solution at the Test spec level:
```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: my-test
  labels:
    group: basic
spec:
  description: "First Test"
  namespace-prefix: "my-test"   # The namespace would look like: my-test-<random-string>-<random-string>
```
Potential solution in Configuration:
```
apiVersion: chainsaw.kyverno.io/v1alpha2
kind: Configuration
metadata:
  name: tests-config
spec:
  namespace-prefix: "my-test"
```

### Alternatives

As of right now, I couldn't find any workaround for this. 

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eolatham** [comment]
Great idea, this would allow the user to override the default prefix of `chainsaw`.

Minor suggestion: maybe the new property name should be `namespacePrefix` instead of `namespace-prefix` to follow the convention of the other properties.

**Comment by eddycharly** [comment]
You can configure it in the config:

```yaml
  namespace:
    template:
      metadata:
        name: (join('-', ['prefix', $namespace]))
```

Would this work ?
