### ISSUE TITLE
[Feature] support outputs transmit to follow steps

### ISSUE THREAD

**Issue by nkuacac** [kyverno/chainsaw#2157]
### Problem Statement

```
steps:
    - try:
      - description: ""
        script:
          ...
          outputs:
            - name: result
              value: (json_parse($stdout).status.result)
    - try:
       - description: "use outputs_result to get before step result"
          apply:
            bindings:
               - name: get_from_before_step
                  value: ($outputs_result)
```

### Solution Description

```
type StepProcessor interface {
	Run(context.Context, namespacer.Namespacer, engine.Context, engine.Context) **engine.Context**
}
```
```
func (p *stepProcessor) Run(ctx context.Context, namespacer namespacer.Namespacer, tc engine.Context, testTc engine.Context) engine.Context {
...
			for k, v := range outputs {
				tc = tc.WithBinding(ctx, k, v)
				**testTc = testTc.WithBinding(ctx, "outputs_"+k, v)**
			}
		}
	}
	return testTc
}
```

### Research

- [X] I have searched other issues in this repository and mine is not recorded.
