### ISSUE TITLE
[Question] Passing values from array of values

### ISSUE THREAD

**Issue by mati-visa** [kyverno/chainsaw#2248]
### Describe your question

Hello, 

Wanna know, how to play with nested values files.

So my question is fairly simple, I've a values.yaml file in given format: 

```yaml
dependencies:
  - name: test
    version: 1.2.3
```

My test looks like these:
```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: is-valid-version
spec:
  steps:
  - try:            
    - assert:
        resource:
          apiVersion: v1
          kind: Pod
          metadata:
            labels:
              version: ($values.dependencies[????])
```

Tried multiple functions and ways but no luck, it could be helpfull to have at least some examples in docs for functions how they work or to have idk some sort of terminal/playground to validate how function work 

### chainsaw version Version

v0.2.12
