### ISSUE TITLE
[Question] interactiveMode must be specified for chainsaw to use exec authentication plugin 

### ISSUE THREAD

**Issue by haarchri** [kyverno/chainsaw#2263]
### Describe your question

i get the following error: 

```
2025/01/14 19:15:27         === STDERR
2025/01/14 19:15:27         error: interactiveMode must be specified for chainsaw to use exec authentication plugin
2025/01/14 19:15:27     l.go:52: | 19:15:27 | apply | Apply Resources          | SCRIPT    | ERROR |
```

my kubeconfig looks something like:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: abc
    server: https://xyz
  name: xyz
contexts:
- context:
    cluster: xyz
    extensions:
    - extension:
        apiVersion: xyz.io/v1alpha1
        kind: Ext
        spec:
          cloud:
            organization: xyz
            space: xyz-gcp-us-central-1
      name: xyz.io/rocket
    namespace: default
    user: xyz
  name: xyz
current-context: xyz
kind: Config
preferences: {}
users:
- name: xyz
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - organization
      - token
      command: xyz
      env:
      - name: ORGANIZATION
        value: xyz
      - name: PROFILE
        value: test
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

```
cat 00-apply.yaml 
# This file belongs to the resource apply step.
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: apply
spec:
  timeouts:
    apply: 1h23m20s
    assert: 1h23m20s
    exec: 1h23m20s
  steps:
  - name: Run Setup Script
    description: Setup the test environment by running the setup script.
    try:
    - command:
        entrypoint: /var/folders/ym/wqrhc4wd0mj6b1wbkc25s0_80000gn/T/xyz-174868208/setup.sh
  - name: Apply Resources
    description: Apply resources to the cluster.
    try:
    - apply:
        file: test-input.yaml
    - script:
        content: |
          echo "Runnning annotation script"
  - name: Assert Status Conditions
    description: |
      Assert applied resources. First, run the pre-assert script if exists.
      Then, check the status conditions. Finally run the post-assert script if it
      exists.
    try:
    - assert:
        resource:
          apiVersion: platform.example.com/v1alpha1
          kind: StorageBucket
          metadata:
            name: example
            namespace: default
          status:
            ((conditions[?type == 'Ready'])[0]):
              status: "True"
```

### chainsaw version Version

v0.2.12
