### ISSUE TITLE
[Bug] Direct template evaluation doesn't work unless the resource is instantiated

### ISSUE THREAD

**Issue by kfernandsap** [kyverno/chainsaw#2282]
### chainsaw version Version

v0.2.12

### Description

 Direct template evaluation doesn't work unless the resource is instantiated.

### Steps to reproduce

1. chainsaw-test.yaml

```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: assert-podinfo-deployment-and-service
spec:
  steps:
    - try:
        - assert:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: podinfo
                namespace: podinfo
                labels:
                  app.kubernetes.io/name: podinfo
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app.kubernetes.io/name: podinfo
                template:
                  metadata:
                    labels:
                      app.kubernetes.io/name: podinfo
                  spec:
                    containers:
                      - name: podinfo
                        image: ghcr.io/stefanprodan/podinfo:($values.imagetag)
```

2. values.yaml
```
imagetag: 6.7.1
```

3. chainsaw test --values ./values.yaml .  

```
Version: 0.2.12
Loading default configuration...
- Using test file: chainsaw-test
- TestDirs [.]
- SkipDelete false
- FailFast false
- Namespace ''
- FullName false
- IncludeTestRegex ''
- ExcludeTestRegex ''
- ApplyTimeout 5s
- AssertTimeout 30s
- CleanupTimeout 30s
- DeleteTimeout 15s
- ErrorTimeout 30s
- ExecTimeout 5s
- DeletionPropagationPolicy Background
- Values [./values.yaml]
- Template true
- NoCluster false
- PauseOnFailure false
Loading tests...
- assert-podinfo-deployment-and-service (.chainsaw-test)
Loading values...
Running tests...
=== RUN   chainsaw
=== PAUSE chainsaw
=== CONT  chainsaw
=== RUN   chainsaw/assert-podinfo-deployment-and-service
=== PAUSE chainsaw/assert-podinfo-deployment-and-service
=== CONT  chainsaw/assert-podinfo-deployment-and-service
    | 11:39:05 | assert-podinfo-deployment-and-service | @chainsaw | CREATE    | OK    | v1/Namespace @ chainsaw-hardy-egret
    | 11:39:05 | assert-podinfo-deployment-and-service | step-1    | TRY       | BEGIN |
    | 11:39:05 | assert-podinfo-deployment-and-service | step-1    | ASSERT    | RUN   | apps/v1/Deployment @ podinfo/podinfo
    | 11:39:35 | assert-podinfo-deployment-and-service | step-1    | ASSERT    | ERROR | apps/v1/Deployment @ podinfo/podinfo
        === ERROR
        ----------------------------------
        apps/v1/Deployment/podinfo/podinfo
        ----------------------------------
        * spec.template.spec.containers[0].image: Invalid value: "ghcr.io/stefanprodan/podinfo:6.7.1": Expected value: "ghcr.io/stefanprodan/podinfo:($values.imagetag)"

        --- expected
        +++ actual
        @@ -16,6 +16,63 @@
                 app.kubernetes.io/name: podinfo
             spec:
               containers:
        -      - image: ghcr.io/stefanprodan/podinfo:($values.imagetag)
        +      - command:
        +        - ./podinfo
        +        - --port=9898
        +        - --cert-path=/data/cert
        +        - --port-metrics=9797
        +        - --grpc-port=9999
        +        - --grpc-service-name=podinfo
        +        - --level=info
        +        - --random-delay=false
        +        - --random-error=false
        +        env:
        +        - name: PODINFO_UI_COLOR
        +          value: '#34577c'
        +        image: ghcr.io/stefanprodan/podinfo:6.7.1
        +        imagePullPolicy: IfNotPresent
        +        livenessProbe:
        +          exec:
        +            command:
        +            - podcli
        +            - check
        +            - http
        +            - localhost:9898/healthz
        +          failureThreshold: 3
        +          initialDelaySeconds: 1
        +          periodSeconds: 10
        +          successThreshold: 1
        +          timeoutSeconds: 5
                 name: podinfo
        +        ports:
        +        - containerPort: 9898
        +          name: http
        +          protocol: TCP
        +        - containerPort: 9797
        +          name: http-metrics
        +          protocol: TCP
        +        - containerPort: 9999
        +          name: grpc
        +          protocol: TCP
        +        readinessProbe:
        +          exec:
        +            command:
        +            - podcli
        +            - check
        +            - http
        +            - localhost:9898/readyz
        +          failureThreshold: 3
        +          initialDelaySeconds: 1
        +          periodSeconds: 10
        +          successThreshold: 1
        +          timeoutSeconds: 5
        +        resources:
        +          requests:
        +            cpu: 1m
        +            memory: 16Mi
        +        terminationMessagePath: /dev/termination-log
        +        terminationMessagePolicy: File
        +        volumeMounts:
        +        - mountPath: /data
        +          name: data
    | 11:39:35 | assert-podinfo-deployment-and-service | step-1    | TRY       | END   |
    | 11:39:35 | assert-podinfo-deployment-and-service | @chainsaw | CLEANUP   | BEGIN |
    | 11:39:35 | assert-podinfo-deployment-and-service | @chainsaw | DELETE    | OK    | v1/Namespace @ chainsaw-hardy-egret
    | 11:39:40 | assert-podinfo-deployment-and-service | @chainsaw | CLEANUP   | END   |
--- FAIL: chainsaw (0.00s)
    --- FAIL: chainsaw/assert-podinfo-deployment-and-service (35.40s)
FAIL
Tests Summary...
- Passed  tests 0
- Failed  tests 1
- Skipped tests 0
Done with failures.
Error: some tests failed
```

### Expected behavior

The test should have taken the value for the imagetag from values.yaml and interpolated in the tests. 

**NOTE:** The service is already created on the cluster.  One only wants to assert that the deployment and service are running correctly for a new version of the app. 

### Logs

```Shell

```

### Troubleshooting

- [x] I have searched other issues in this repository and mine is not recorded.
