### ISSUE TITLE
[Feature] enable skipping step based on condition

### ISSUE THREAD

**Issue by rahulait** [kyverno/chainsaw#2297]
### Problem Statement

We would like to have a way to skip a step by just setting skip on a step. Currently, we can't find any way to skip a step within a test. We can use script within step and have the logic within it to skipp based on env vars, but we would like to support skipping steps which don't use script.

### Solution Description

We want to have something like:
```
  steps:
    - name: Check if resource is deployed
      skip: <based on some env var>
      try:
        - assert:
            file: ../assert-resources.yaml
```
Here, having `skip: true/false` can be used to skip the step and continue.

### Slack discussion

https://kubernetes.slack.com/archives/C067LUFL43U/p1738165539650759

### Research

- [x] I have searched other issues in this repository and mine is not recorded.
