### ISSUE TITLE
[Feature] Expose timeouts as bindings

### ISSUE THREAD

**Issue by jneuff** [kyverno/chainsaw#2371]
### Problem Statement

Hi,

it would be helpful to expose the timeouts as bindings. Let's say I do a `helm install` as part of my test:

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: should-install
spec:
  timeouts:
    exec: 1m
  steps:
    - try:
      - command:
          entrypoint: helm
          env:
            - name: NAMESPACE
              value: ($namespace)
          args:
            - install
            - my-test
            - ../helm/test-chart
            - --namespace
            - $NAMESPACE
            - --wait
            - --timeout
            - 1m
```

I have to set the correct timeout twice which is error prone.

### Solution Description

Exposing the timeouts as bindings would help simplify the example from above:

```yaml
spec:
  timeouts:
    exec: 1m
  steps:
    - try:
      - command:
          entrypoint: helm
          env:
            - name: NAMESPACE
              value: ($namespace)
           - name: TIMEOUT
             value: ($timeout-exec)
          args:
            - install
            - my-test
            - ../helm/test-chart
            - --namespace
            - $NAMESPACE
            - --wait
            - --timeout
            - $TIMEOUT
```

### Research

- [x] I have searched other issues in this repository and mine is not recorded.
