### ISSUE TITLE
Assert with FileRef from github

### ISSUE THREAD

**Issue by fab7** [kyverno/chainsaw#563]
#### Description
Configuration files are often located in github and when one needs to assert them, he first need to download them via `curl` or `wget`. This costs a lot of typing and is error prone. 
Therefore, it would be nice if the `FileRef` could be provided as a reference to a raw file in github.

#### To Reproduce (in v0.0.6)
```
steps:
  - name: "Retrieve raw file from github"
    try:
      - script:
          content: | 
            curl https://raw.githubusercontent.com/kyverno/chainsaw/v0.0.6-alpha.4/testdata/test/custom-test.yaml -o ./local-custom-test.yaml
  - name: "Assert the downloaded version of the file"
    try:
      - assert:
          file: ./local-custom-test.yaml
```
 
#### Expected enhancement
```
steps:
  - name: "Assert from a raw github file"
    try:
      - assert:
          file: https://raw.githubusercontent.com/kyverno/chainsaw/v0.0.6-alpha.4/testdata/test/custom-test.yaml
```
