### ISSUE TITLE
Asserting command output that is YAML

### ISSUE THREAD

**Issue by chipzoller** [kyverno/chainsaw#570]
## Problem

Helm has had a legacy of breaking the ability to [delete keys through values overrides](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key). The latest incident is logged in https://github.com/helm/helm/issues/12469 in which setting `null` does not delete a key in a subchart. Testing for this in Helm's CI processes could be very easy with the help of either Chainsaw or [Kyverno-JSON](https://github.com/kyverno/kyverno-json).

## Objective

Write a test in the simplest way possible which runs a command such as `helm template foo/ -s charts/foo/templates/bar.yaml --set global.foo.bar=null` and checks that the output in the `bar.yaml` template of the `foo` subchart's `foo.bar` field has been set to `null`. If the value in the templated YAML output of `foo.bar` is set to `null` then the test passes. If the value is anything else other than `null`, the test fails.

Helm does not have an ability to change the output format from YAML to JSON, so if this isn't a valid use case for Chainsaw then testing would be slightly more complex with Kyverno-JSON as the output would have to be piped to something like `yq` to convert to JSON, then test. EDIT: It seems like Kyverno-JSON works with YAML natively so that's nice.

**Comment by eddycharly** [comment]
@chipzoller is there anything we should do in chainsaw ? we already provide access to the command STDOUT and STDERR streams and functions to help parsing the output, not sure how we can make it better 🤔

**Comment by chipzoller** [comment]
Maybe this is just a use case where it is necessary to chain several tools together to get the desired outcome.

**Comment by eddycharly** [comment]
We recently started to use chainsaw for testing kyverno-json.
We use `json_parse($stdout)` but would work with `yaml_parse($stdout)` too.

Here is a test example:

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: bad-test
spec:
  steps:
    - name: kyverno-json
      try:
      - script:
          content: |
            set -e
            kyverno-json scan --policy ../check-allow-untrusted-flag.yaml --payload ./bad-test/bad-payload.json --output json
          check:
            ($error): ~
            (json_parse($stdout)):
            - results:
              - policy:
                  apiVersion: json.kyverno.io/v1alpha1
                  kind: ValidatingPolicy
                  metadata:
                    name: detect-untrusted-flag
                rules:
                - rule:
                    name: detect-untrusted-flag
                  error: ~
                  violations:
                  - message: Dockerfile contains the '--allow-untrusted' which is not preferred
                    errors:
                    - type: FieldValueInvalid
                      value: true
                      detail: 'Expected value: false'
```
