### ISSUE TITLE
Add warnings check support

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#647]
Add warnings check support.

**Comment by swastik959** [comment]
@eddycharly can you please explain this issue to me

**Comment by chriswhite199** [comment]
I can expand here as I'm also looking for this feature.

When testing admission controllers, the controller can send back warnings associated with a resource, for example you have a CRD with a deprecated field or some other non fatal warning you want to convey to the caller.

These warnings are returned to the caller in an HTTP header named Warning. This header can be repeated multiple times:

```
Warning: 299 - "Some warning about the resource"
Warning: 299 - "another warning"
```

What would be nice is if these warnings could be checked in a chainsaw test, something like this:

```yaml
expect:
  - check
      (contains($warnings, 'another warning'))
```

How you'd handle the fact that warnings could be an array (where the header can be repeated) or whether you just newline-delim the header values, I'm open to suggestions

**Comment by chriswhite199** [comment]
For those looking for a short term solution, you can just use a script step to call kubectl, and check the content of the $stderr field.

This isn't ideal as you can't easily template the resource being passed to kubectl, but works in a pinch

**Comment by chriswhite199** [comment]
Digging through the code, it seems this could be possible by registering a WarningsHandler callback in the go client, but the issue then would be that you would need a single client instance per thread (as you would need to correlate the callback invocations with the client requests made)

* https://github.com/kubernetes/client-go/blob/master/rest/config.go#L139

**Comment by chriswhite199** [comment]
POC: https://github.com/kyverno/chainsaw/compare/main...chriswhite199:chainsaw:main

* Comments welcome (I'm not a Go programmer)
* Only implemented for the Apply operation, no unit tests and existing tests fail

Test suite (that passes)

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: warnings-example
spec:
  steps:
  - try:
    - apply:
        # CRD with a deprecated version to allow testing of warnings capture
        resource:
          apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          metadata:
            name: crontabs.stable.example.com
          spec:
            group: stable.example.com
            versions:
              - name: v1
                served: true
                storage: false
                deprecated: true
                deprecationWarning: "example.com/v1 CronTab is deprecated"
                schema:
                  openAPIV3Schema:
                    type: object
                    properties:
                      spec:
                        type: object
                        properties:
                          cronSpec:
                            type: string
                          image:
                            type: string
                          replicas:
                            type: integer
              - name: v2
                served: true
                storage: true
                schema:
                  openAPIV3Schema:
                    type: object
                    properties:
                      spec:
                        type: object
                        properties:
                          cronSpec:
                            type: string
                          image:
                            type: string
                          replicas:
                            type: integer
            scope: Namespaced
            names:
              plural: crontabs
              singular: crontab
              kind: CronTab
              shortNames:
              - ct

    - assert:
        # wait for CRD to be available
        resource:
          apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          metadata:
            name: crontabs.stable.example.com
          status:
            acceptedNames:
              kind: CronTab
              plural: crontabs
              singular: crontab
  - try:
    # create deprecated version of CRD kind
    - apply:
        resource:
          apiVersion: "stable.example.com/v1"
          kind: CronTab
          metadata:
            name: my-new-cron-object
          spec:
            cronSpec: "* * * * */5"
            image: my-awesome-cron-image
        # API server should return warning about deprecated version
        expect:
          - check:
              ( $warnings[] | length(@) ): 1
              ( $warnings[0].text | contains(@, 'CronTab is deprecated') ): true

```
