### ISSUE TITLE
[Feature] : Use Directory Path Ref in operation like apply, assert etc. 

### ISSUE THREAD

**Issue by shubham-cmyk** [kyverno/chainsaw#794]
### Problem Statement

Currently we support the struct : `FileRefOrResource` in which we can only specify the file reference not the complete directory. 
Which makes us to write all the files explicitly which we want to use in a particular operation. 

### Solution Description

Use something like `directoryRef` in which we can specify the path to the directory in which we contain all the manifest to be applied during the operation.

### Slack discussion

https://kubernetes.slack.com/archives/C067LUFL43U/p1706995405247079

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dcristobalhMad** [comment]
Another option would be to use a file regex, perhaps this would work better for specific cases (example of gitops and you only want to test certain files within the folder). Something like this perhaps:

```
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: clusterrolebindings
spec:
  steps:
  - try:
    # create resources in the cluster, in resources path there may be several deployments of one application and several deployments of another application.
    - apply:
        file: resources/*appA.yaml
    # verify the operator reacted as expected
    - assert:
        file: expected.yaml
```
Another added feature would be to use a recursive flag to be able to test files in folders and subfolders, I don't know what you think but it could be a good feature for a next iteration.
Thanks!
