### ISSUE TITLE
[Tracker] : Breaking Changes in API

### ISSUE THREAD

**Issue by shubham-cmyk** [kyverno/chainsaw#837]
### Problem Statement

Need a track the required api changes

### Solution Description

A tracker to collect the breaking changes in API's in the next major release.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
You may want to standardize on how to refer to existing cluster resources across all operations so you avoid having to do this:

```yaml
  - name: 04 - Delete good PDBs
    try:
    - delete:
        ref:
          apiVersion: policy/v1
          kind: PodDisruptionBudget
          name: good-pdb01
  - name: 05 - Update existing Deployments to have one replica
    try:
    - patch:
        resource:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: alpha-busybox
          spec:
            replicas: 1
```
