### ISSUE TITLE
[Feature] Variables inside `Test`

### ISSUE THREAD

**Issue by vfarcic** [kyverno/chainsaw#954]
### Problem Statement

I'd like to be able to reuse `apply` and `assert` manifests across `Test` instances.

### Solution Description

Here's a mock proposal that shows what I'm looking for (ignore the syntax):

```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: aws
spec:
  vars:
    foo: bar
  steps:
    - try:
        - apply:
            file: ../common/00-install.yaml
        - assert:
            file: ../common/00-assert.yaml
        - assert:
            file: 00-assert.yaml
```

The addion of `spec.vars` would allow me to template common `apply` and `assert` manifests (e.g., `../common/00-install.yaml`, `../common/00-assert.yaml`) while still maintaining those that are specific to that instance of `Test` (e.g., `00-assert.yaml`)

### Alternatives

Generate variations of manifests with CUE or Helm before running tests.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
Those are bindings, something like this would be good:
```yaml
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: aws
spec:
  bindings:
    foo: bar
  steps:
    - try:
        - apply:
            file: ../common/00-install.yaml
        - assert:
            file: ../common/00-assert.yaml
        - assert:
            file: 00-assert.yaml
```

**Comment by eddycharly** [comment]
One thing to keep in mind though is bindings dependency, for example:

```yaml
  bindings:
    a: 1
    b: 2
    c: ($a + $b)
```

For this reason i would tend to use something like this:

```yaml
  bindings:
  - name: a
     value: 1
  - name: b
     value: 1
  - name: c
     value: ($a + $b)
```

WDYT @vfarcic ?
