### ISSUE TITLE
[Bug] `kind` in aray assertions

### ISSUE THREAD

**Issue by vfarcic** [kyverno/chainsaw#955]
### chainsaw version Version

v0.1.6

### Description

Given the following YAML:

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: xyz
  labels:
    crossplane.io/claim-name: my-db
spec:
  resourceRefs:
    - apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Database
      name: my-db-aws-db-01
    - apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Database
      name: my-db-aws-db-02
    - apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTable
      name: my-db-aws
```

The following assert works (fails correctly):

```yaml
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  parameters:
    databases:
      - db-01
      - db-02
      - db-03
  ~index.(resourceRefs[?apiVersion == 'postgresql.sql.crossplane.io/v1alpha1']):
    name: (join('-', ['my-db-aws-db-0xxx', to_string($index + `1`)]))
```

The name should not contain `xxx`.

However, the following assertion does not work (does not fail):

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  parameters:
    databases:
      - db-01
      - db-02
      - db-03
  ~index.(resourceRefs[?kind == 'Database']):
    name: (join('-', ['my-db-aws-db-0xxx', to_string($index + `1`)]))
```

The difference is that I'm querying it by `kind` instead of `apiVersion`. It did not find any entries that match it even though it should (I think). Is there something "special" about using `kind` as the field name?

I guess I'm doing something wrong, but I cannot figure out what.

Besides that issue, is there a way to validate that a specific number of entries is found matching that expression?

### Steps to reproduce

1. That specific example might be hard to reproduce since it requires Crossplane and specific Compositions.

### Expected behavior

Asserts should fail in both cases.

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
> is there a way to validate that a specific number of entries is found matching that expression?

@vfarcic you can use the `length` function.

Something like:

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  parameters:
    databases:
      - db-01
      - db-02
      - db-03
  (resourceRefs[?kind == 'Database']):
    (length(@)): 2
    ~index.(@):
      name: (join('-', ['my-db-aws-db-0xxx', to_string($index + `1`)]))
```

**Comment by eddycharly** [comment]
I will try it later we have a `chainsaw assert` command to test this kind of things with manifests (no need for crossplane).

**Comment by eddycharly** [comment]
Maybe something in golang `reflect` package interferes with the jmespath lib, will check.

**Comment by eddycharly** [comment]
@vfarcic i tried with `chainsaw assert -r resource.yaml -f assert.yaml`:

resource.yaml

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: xyz
  labels:
    crossplane.io/claim-name: my-db
spec:
  resourceRefs:
    - apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Database
      name: my-db-aws-db-01
    - apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Database
      name: my-db-aws-db-02
    - apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTable
      name: my-db-aws
```

assert.yaml

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  ~index.(resourceRefs[?kind == 'Database']):
    name: (join('-', ['my-db-aws-db-0xxx', to_string($index + `1`)]))
```

The result looks correct:

```
Error: assertion failed:
----------------------------------------
devopstoolkitseries.com/v1alpha1/SQL/xyz
----------------------------------------
* spec.~index.(resourceRefs[?kind == 'Database'])[0].name: Invalid value: "my-db-aws-db-01": Expected value: "my-db-aws-db-0xxx-1"
* spec.~index.(resourceRefs[?kind == 'Database'])[1].name: Invalid value: "my-db-aws-db-02": Expected value: "my-db-aws-db-0xxx-2"

--- expected
+++ actual
@@ -3,7 +3,6 @@
 metadata:
   labels:
     crossplane.io/claim-name: my-db
-spec:
-  ~index.(resourceRefs[?kind == 'Database']):
-    name: (join('-', ['my-db-aws-db-0xxx', to_string($index + `1`)]))
+  name: xyz
+spec: {}
 ```

**Comment by vfarcic** [comment]
This is strange. The following does not work (it does not fail):

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  claimRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQLClaim
    name: my-db
  compositionRef:
    name: aws-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: aws
  compositionUpdatePolicy: Automatic
  id: my-db-aws
  parameters:
    size: medium
    version: "13.4"
  ~index.(resourceRefs[?kind == 'Database']):
    name: (join('-', ['my-db-aws-db-0xxx', to_string($index + `1`)]))
  # resourceRefs:
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: InternetGateway
  #   name: my-db-aws
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: MainRouteTableAssociation
  #   name: my-db-aws
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: RouteTableAssociation
  #   name: my-db-aws-1a
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: RouteTableAssociation
  #   name: my-db-aws-1b
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: RouteTableAssociation
  #   name: my-db-aws-1c
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: RouteTable
  #   name: my-db-aws
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: Route
  #   name: my-db-aws
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: SecurityGroupRule
  #   name: my-db-aws
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: SecurityGroup
  #   name: my-db-aws
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: Subnet
  #   name: my-db-aws-a
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: Subnet
  #   name: my-db-aws-b
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: Subnet
  #   name: my-db-aws-c
  # - apiVersion: ec2.aws.upbound.io/v1beta1
  #   kind: VPC
  #   name: my-db-aws
  # - apiVersion: kubernetes.crossplane.io/v1alpha1
  #   kind: ProviderConfig
  #   name: my-db-aws-sql
  # - apiVersion: kubernetes.crossplane.io/v1alpha2
  #   kind: Object
  #   name: my-db-aws-secret
  # - apiVersion: postgresql.sql.crossplane.io/v1alpha1
  #   kind: Database
  #   name: my-db-aws-db-01
  # - apiVersion: postgresql.sql.crossplane.io/v1alpha1
  #   kind: Database
  #   name: my-db-aws-db-02
  # - apiVersion: postgresql.sql.crossplane.io/v1alpha1
  #   kind: Database
  #   name: my-db-aws-db-03
  # - apiVersion: postgresql.sql.crossplane.io/v1alpha1
  #   kind: ProviderConfig
  #   name: my-db-aws
  # - apiVersion: rds.aws.upbound.io/v1beta1
  #   kind: Instance
  #   name: my-db-aws
  # - apiVersion: rds.aws.upbound.io/v1beta1
  #   kind: SubnetGroup
  #   name: my-db-aws
```

However, if I uncomment the old entries, it works (it fails).
