### ISSUE TITLE
 [Docs]: Functions Example in Docs

### ISSUE THREAD

**Issue by vfarcic** [kyverno/chainsaw#957]
### Problem Statement

It's not clear how to use functions based on https://kyverno.github.io/chainsaw/latest/jp/functions/.

### Solution Description

Add a few examples to the docs.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by shubham-cmyk** [comment]
@vfarcic We have some examples here. 
https://github.com/kyverno/chainsaw/tree/main/testdata/e2e/examples

we can make a specific directory here `functions` to display the use of everyfunction :)

**Comment by vfarcic** [comment]
That would be great. What I'm looking for is an example of `contains`. I'm hoping that I could use it to validate whether an array contains specific entries. My arrays have tens or more entries and listing them all tends to be cumbersome.

**Comment by shubham-cmyk** [comment]
```
(contains($stdout, '[OK] All 16384 slots covered.')): true
```

complete test : https://github.com/OT-CONTAINER-KIT/redis-operator/blob/db14d1b018b2fd0f62485bd2f8bd9b376c81dc10/tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/chainsaw-test.yaml#L66

**Comment by shubham-cmyk** [comment]
assert manifest ? 
why would you need a check on the assert manifest.

**Comment by eddycharly** [comment]
currently we generate the docs from the code... i will see if i can improve that in the jp lib, i agree this is a bit poor ;)

**Comment by shubham-cmyk** [comment]
i think we can.

**Comment by vfarcic** [comment]
Here's a manifest:

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: xyz
spec:
  claimRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQLClaim
    name: my-db
  compositionRef:
    name: aws-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: aws
  compositionUpdatePolicy: Automatic
  id: my-db-aws
  parameters:
    size: medium
    version: "13.4"
  resourceRefs:
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: InternetGateway
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: MainRouteTableAssociation
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: RouteTableAssociation
    name: my-db-aws-1a
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: RouteTableAssociation
    name: my-db-aws-1b
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: RouteTableAssociation
    name: my-db-aws-1c
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: RouteTable
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: Route
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: SecurityGroupRule
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: SecurityGroup
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: Subnet
    name: my-db-aws-a
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: Subnet
    name: my-db-aws-b
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: Subnet
    name: my-db-aws-c
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: VPC
    name: my-db-aws
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: ProviderConfig
    name: my-db-aws-sql
  - apiVersion: kubernetes.crossplane.io/v1alpha2
    kind: Object
    name: my-db-aws-secret
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: Database
    name: my-db-aws-db-01
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: Database
    name: my-db-aws-db-02
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: Database
    name: my-db-aws-db-03
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: ProviderConfig
    name: my-db-aws
  - apiVersion: rds.aws.upbound.io/v1beta1
    kind: Instance
    name: my-db-aws
  - apiVersion: rds.aws.upbound.io/v1beta1
    kind: SubnetGroup
    name: my-db-aws
```

I'd like to check that, among other things, that resource contains `spec.resourceRefs[].kind: InternetGateway` without having to specify all the items in `spec.resourceRefs`.

**Comment by shubham-cmyk** [comment]
```

apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: example
spec:
  steps:
  - try:
    # ...
    - assert:
        resource:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: foo
          spec:
            (replicas > 3): true
    # ...

```

refer : https://kyverno.github.io/chainsaw/main/operations/assert/#usage-in-test


Would this example help

**Comment by eddycharly** [comment]
@vfarcic you can do something like this:

```
(contains(spec.resourceRefs[?kind == InternetGateway].[name], ['my-db-aws'])): true
```

(it's called multiselect in jmespath term)

**Comment by vfarcic** [comment]
Would something like the following be it?

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  claimRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQLClaim
    name: my-db
  compositionRef:
    name: aws-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: aws
  compositionUpdatePolicy: Automatic
  id: my-db-aws
  parameters:
    size: medium
    version: "13.4"
  (contains(resourceRefs[?kind == InternetGateway].[name], ['my-db-aws'])): true
  resourceRefs:
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: InternetGateway
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: MainRouteTableAssociation
    name: my-db-aws
  - apiVersion: ec2.aws.upbound.io/v1beta1
    kind: RouteTableAssociation
    name: my-db-aws-1a
```

That one is throwing `* spec.(contains(resourceRefs[?kind == InternetGateway].[name], ['my-db-aws'])): Invalid value: false: Expected value: true`.

I left the existing `resourceRef` there as a reference. Without the `contains` line it works so the `InternetGateway` is definitely there.

**Comment by eddycharly** [comment]
Tried it, with quotes it passes:

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  claimRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQLClaim
    name: my-db
  compositionRef:
    name: aws-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: aws
  compositionUpdatePolicy: Automatic
  id: my-db-aws
  parameters:
    size: medium
    version: "13.4"
  (length(resourceRefs[?kind == 'InternetGateway'])): 1
  (contains(resourceRefs[?kind == 'InternetGateway'].[name], ['my-db-aws'])): true
```

**Comment by eddycharly** [comment]
@vfarcic there's a simpler and more elegant solution:

```yaml
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  claimRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQLClaim
    name: my-db
  compositionRef:
    name: aws-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: aws
  compositionUpdatePolicy: Automatic
  id: my-db-aws
  parameters:
    size: medium
    version: "13.4"
  (resourceRefs[?kind == 'InternetGateway']):
  - name: my-db-aws
```
