### ISSUE TITLE
[Feature] Support template variables interpolation

### ISSUE THREAD

**Issue by cezarsa** [kyverno/chainsaw#995]
### Problem Statement

Hey folks, would it be possible to support interpolating templated values with other string values. Here is an example of what I would like to do:

```
apiVersion: v1
data:
  myvar: ($values.myvar)-hardcoded-suffix
kind: ConfigMap
metadata:
  name: myconfigmap
type: Opaque
```

Currently, this only works using the template variable as the full value: `myvar: ($values.myvar)`

### Solution Description

Support interpolating templated variables in the middle of strings.

### Alternatives

The alternative would be to have a new `$values` var for each possible string.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
You can use the `join` function:

```yaml
apiVersion: v1
data:
  myvar: (join('-', [$values.myvar, 'hardcoded-suffix']))
kind: ConfigMap
metadata:
  name: myconfigmap
type: Opaque
```
